CODEDEX EXCERCISES


In [14]:

import numpy as np



ARITHMETIC OPERATIONS

The world’s tallest buildings are the following, convert them to meters

In [16]:
tallest_buildings = np.array([2717, 2227, 2073, 1972, 1966, 1819, 1776])
print(tallest_buildings)
print("after conversion to meters:")
print(tallest_buildings*0.3048)


[2717 2227 2073 1972 1966 1819 1776]
after conversion to meters:
[828.1416 678.7896 631.8504 601.0656 599.2368 554.4312 541.3248]


NumPy Functions



Here are some of the common ones:

- .min() Return the minimum value of an array.
- .max() Return the maximum value of an array.
- .sum() Return the total sum of an array's values.
- .average() Return the average value of an array.

Go into your phone and find the number of steps you’ve taken in the last week and add them into an array.

In [17]:
steps = np.array([3191, 230, 9193, 4670, 164, 3820, 9093])

In [20]:
print(f" the minimum no of steps is { np.min(steps)}")
print(f" the maximum no of steps is { np.max(steps)}")
print(f" the average no of steps is { round(np.average(steps))}")

 the minimum no of steps is 164
 the maximum no of steps is 9193
 the average no of steps is 4337


SHAPE

In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]) 

print(arr.shape)    

(4, 3)


reshape

In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]) 
new_arr = arr.reshape(2, 4)

print(new_arr)



[[1 2 3 4]
 [5 6 7 8]]


#30NitesOfCode is a feature on Codédex that encourages one to code every day for a month.

A learner completed the challenge and recorded the amount of time they coded every single day for four weeks:
- 56
- 100 
- 33 
- 0
- 45
- 45
- 46
- 34
- 89,
- 180
- 60
- 45
- 45
- 44
- 46
- 45
- 0
- 0
- 15
- 90
- 301
- 197
- 20
- 60
- 45
- 45
- 42
- 45

what is the shape of this array? Confirm by using the .shape property.

In [25]:
month_results = np.array([56, 100, 33, 0, 45, 45, 46, 34, 89, 180, 60, 45, 45, 44, 46, 45, 0, 0, 15, 90, 301, 197, 20, 60, 45, 45, 42, 45])

In [26]:
month_results.shape

(28,)

Suppose we want to split this monthly data into weekly data. Use .reshape() so that each row is made of 7 items (for each week of the month).

In [27]:
month_results.reshape(4,7)

array([[ 56, 100,  33,   0,  45,  45,  46],
       [ 34,  89, 180,  60,  45,  45,  44],
       [ 46,  45,   0,   0,  15,  90, 301],
       [197,  20,  60,  45,  45,  42,  45]])

.arange()

Halley's Comet is a comet visible from Earth every 75 years. It is the only known "short-period comet" that is consistently visible to the naked eye from Earth. It was last seen in 1986 and the next one will happen in 2061. 💫

Using .arange(), create an array of numbers with the years when Halley's Comet will appear next from year 1986 to 3000.

In [28]:
comet_visible=np.arange(start=1986, stop=3001, step=75)
print(comet_visible)

[1986 2061 2136 2211 2286 2361 2436 2511 2586 2661 2736 2811 2886 2961]


we learned:

Math operations with +, -, *, /, and %.
Math functions like .min(), .max(), .sum(), .average().
.shape shows the number of elements for each dimension and .reshape() updates it.
.arange() to create an array with evenly spaced values.

TITANIC ANALYSIS

- What is the shape of this array?
- What is the average age of the passengers?
- What is the passenger number of the oldest passenger? Who is the youngest?
- What is the percentage of folks that survived?

In [29]:
passengers = np.array([
   [1, 0, 3, 22],
   [2, 1, 1, 38],
   [3, 1, 3, 26],
   [4, 1, 1, 35],
   [5, 0, 3, 35],
   [6, 0, 3, 18],
   [7, 0, 1, 54],
   [8, 0, 3, 2],
   [9, 1, 3, 27],
  [10, 1, 2, 14],
  [11, 1, 3, 4],
  [12, 1, 1, 58],
  [13, 0, 3, 20],
  [14, 0, 3, 39],
  [15, 0, 3, 14],
  [16, 1, 2, 55],
  [17, 0, 3, 2],
  [18, 1, 2, 12],
  [19, 0, 3, 31],
  [20, 1, 3, 8],
  [21, 0, 2, 35],
  [22, 1, 2, 34],
  [23, 1, 3, 15],
  [24, 1, 1, 28],
  [25, 0, 3, 8],
  [26, 1, 3, 38],
  [27, 0, 3, 2],
  [28, 0, 1, 1],
  [29, 1, 3, 5],
  [30, 0, 3, 18],
  [31, 0, 1, 40],
  [32, 1, 1, 70],
  [33, 1, 3, 33],
  [34, 0, 2, 66],
  [35, 0, 1, 28],
  [36, 0, 1, 42],
  [37, 1, 3, 5],
  [38, 0, 3, 18],
  [39, 0, 3, 18],
  [40, 1, 3, 14],
  [41, 0, 3, 40],
  [42, 0, 2, 27],
  [43, 0, 3, 29],
  [44, 1, 2, 0],
  [45, 1, 3, 19],
  [46, 0, 3, 33],
  [47, 0, 3, 14],
  [48, 1, 3, 22],
  [49, 0, 3, 41],
  [50, 0, 3, 18]
])

In [30]:
passengers.shape

(50, 4)

In [35]:
age=passengers[:, 3]
average_age=np.mean(age)
print(f"The average age of the passengers is {average_age}")


The average age of the passengers is 25.5


In [38]:
age.max()

np.int64(70)

In [45]:
oldest_age = np.max(age)             # maximum age
oldest_index = np.argmax(age)        # index of max age
oldest_passenger = passengers[oldest_index, 0]  # Passenger ID
print("Oldest passenger ID:", oldest_passenger, "Age:", oldest_age)


Oldest passenger ID: 32 Age: 70


In [ ]:
oldest_age = np.min(age)             # maximum age
oldest_index = np.argmin(age)        
oldest_passenger = passengers[oldest_index, 0]  # Passenger ID
print("Oldest passenger ID:", oldest_passenger, "Age:", oldest_age)

Oldest passenger ID: 44 Age: 0


In [44]:
total_passengers = passengers.shape[0]
survived_count = np.sum(passengers[:, 1] == 1)   # count of passengers who survived
survived_percentage = (survived_count / total_passengers) * 100

print("Percentage of passengers who survived:", survived_percentage)


Percentage of passengers who survived: 44.0
