CODEDEX EXCERCISES


In [ ]:

import numpy as np



numpy array

In [3]:
rent = np.array([1500, 1500, 1500, 1500, 1750, 1750])

indexing of arrays in numpy

In [4]:
languages=np.array(['Python', 'Java', 'JavaScript', 'C++', 'Ruby'])
languages[2]

np.str_('JavaScript')

slice

In [5]:
coffee = np.array([3, 2, 1, 0, 1])

print(coffee[0:2])
print(coffee[2:])   
print(coffee[-2:])

[3 2]
[1 0 1]
[0 1]


excercise

Every metro city's population is constantly changing. Google your favorite city's population in the recent years and create an array for them.

Here are the NYC population from 2023 (top) to 2013 (bottom):

19571216
19673200
19854526
20104710
19463131
19544098
19593849
19636391
19657321
19653431
19626488
Print the first item and the last item. What did you get?

Now find the difference between them using subtraction. How did the population change in the last ten years?

COVID-19 happened during 2020-2022; those were some crazy years. Use slicing, and print the population during those years for your city.

In [7]:
population=np.array([19571216,19673200,19854526,20104710,19463131,19544098,19593849,19636391,19657321,19653431,19626488])

In [8]:
print(population[0])

19571216


In [9]:
print(population[-1])

19626488


In [10]:
print(population[1]-population[0])

101984


In [11]:
print(population[1:4])

[19673200 19854526 20104710]


2d arrays

In [12]:
numbers=np.array([[1,2,3],[4,5,6],[7,8,9]])
numbers

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Think of something that you do within a day or within a week that can be observered with some number. Some inspirations could be:

🍵 Recording your mood (out of 10) in each waking hour today.
💤 How many hours you slept.
💧 The number of glasses of water you drink everyday this week.
🥱 The number of yawns.
Use your phone's notes or a notebook to capture this data and then store them in an array.

Does this make sense to keep this data in a 1D array or a 2D array?

Now, use index and slicing to analyze it a bit - what is the average number during waking hours? How about what is the difference between the beginning and the end of the duration?

In [13]:
sleep=np.array([[6,6,7,5,6,7,9]
                ,[7,5,6,8,9,5,6],
                [8,9,5,6,7,8,5]])
print(sleep)

[[6 6 7 5 6 7 9]
 [7 5 6 8 9 5 6]
 [8 9 5 6 7 8 5]]


In [10]:
avg=np.average(sleep)
print(f'The average sleeping time is {round(avg)} hours')

The average sleeping time is 7 hours


row wise

In [11]:
avg=np.average(sleep,axis=1)
print(f'The average sleeping time is {round(avg[0])} hours for the first week')
print(f'The average sleeping time is {round(avg[1])} hours for the second week')
print(f'The average sleeping time is {round(avg[2])} hours for the third week')

The average sleeping time is 7 hours for the first week
The average sleeping time is 7 hours for the second week
The average sleeping time is 7 hours for the third week
